name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          export BUILD_DATE=$(date "+%4Y-%m-%d %H:%M:%S")
          export REPOSITORY=
          export TIMESTAMP=$(date "+%4Y%m%d%H%M%S")
          docker build \
            --tag ghcr.io/${GITHUB_REPOSITORY}:latest \
            --build-arg BUILD_NUMBER='${GITHUB_RUN_NUMBER}' \
            --build-arg TAG='sogo' \
            --build-arg VCS_REF='${GITHUB_SHA}' \
            --build-arg BUILD_DATE="${BUILD_DATE}" \
            --file Containerfile \
            .
          docker tag ghcr.io/${GITHUB_REPOSITORY}:latest \
            ghcr.io/${GITHUB_REPOSITORY}:${TIMESTAMP}
          docker push ghcr.io/${GITHUB_REPOSITORY}:${TIMESTAMP}
          docker push ghcr.io/${GITHUB_REPOSITORY}:latest

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
