name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: 'Build Container Image'
        shell: bash
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          export DEBIAN_VER="12"
          export BUILD_DATE=$(date "+%4Y-%m-%d %H:%M:%S")
          export TIMESTAMP=$(date "+%4Y%m%d%H%M%S")
          export SOGO_VER=$(curl --silent https://api.github.com/repos/Alinto/sogo/releases/latest | jq -r '.tag_name | split("-")[1]')
          podman build \
            --tag sogo \
            --build-arg BUILD_NUMBER='${GITHUB_RUN_NUMBER}' \
            --build-arg TAG='sogo' \
            --build-arg DEBIAN_VER='${DEBIAN_VER}' \
            --build-arg SOGO_VER='${SOGO_VER}' \
            --build-arg VCS_REF='${GITHUB_SHA}' \
            --build-arg BUILD_DATE="${BUILD_DATE}" \
            --file Containerfile \
            .
          podman push --creds="${GITHUB_REPOSITORY_OWNER}:${GHCR_TOKEN}" \
            sogo docker://ghcr.io/${GITHUB_REPOSITORY_OWNER}/sogo:${SOGO_VER}-debian-${DEBIAN_VER}-r${GITHUB_RUN_NUMBER}
          podman push --creds="${GITHUB_REPOSITORY_OWNER}:${GHCR_TOKEN}" \
            sogo docker://ghcr.io/${GITHUB_REPOSITORY_OWNER}/sogo:latest

      - name: 'Package Helm Chart'
        shell: bash
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          export chart_name=$(yq eval -r '.name' charts/sogo/Chart.yaml)
          export chart_version=$(yq eval -r '.version' charts/sogo/Chart.yaml)
          helm package charts/sogo --dependency-update
          echo ${GHCR_TOKEN} | helm registry login --username ${GITHUB_REPOSITORY_OWNER} --password-stdin ghcr.io
          helm push ${chart_name}-${chart_version}.tgz oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/
